name:                aoc2019
version:             0.1.0.0
github:              "nilsalex/aoc2019"
license:             MIT
author:              "Nils Alex"
maintainer:          "nils [at] famalex (tld for germany)"
copyright:           "2020 Nils Alex"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/aoc2019#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- transformers
- parallel
- PSQueue
- deepseq
- network
- bytestring

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -fwarn-unused-imports

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    dependencies:
    - aoc2019
